# Generated by Django 2.2.3 on 2020-02-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_name', models.CharField(max_length=20)),
                ('bin_location', models.CharField(max_length=20)),
                ('bin_contents', models.CharField(max_length=200)),
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_name', models.CharField(max_length=20)),
                ('card_owner', models.CharField(choices=[('r', 'Regent'), ('vr', 'Vice Regent'), ('s', 'Scribe'), ('t', 'Treasurer'), ('cs', 'Corresponding Secretary'), ('ig', 'Inner Guard'), ('og', 'Outer Guard'), ('m', 'Marshal'), ('o', 'Other')], max_length=2)),
                ('card_location', models.CharField(max_length=20)),
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=50)),
                ('item_location', models.CharField(max_length=50)),
                ('item_qty', models.IntegerField(default=1)),
                ('item_longdescription', models.CharField(max_length=300)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key_name', models.CharField(max_length=20)),
                ('key_owner', models.CharField(choices=[('r', 'Regent'), ('vr', 'Vice Regent'), ('s', 'Scribe'), ('t', 'Treasurer'), ('cs', 'Corresponding Secretary'), ('ig', 'Inner Guard'), ('og', 'Outer Guard'), ('m', 'Marshal'), ('o', 'Other')], max_length=2)),
                ('key_location', models.CharField(max_length=50)),
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=20)),
                ('note_stamp', models.DateTimeField(auto_now_add=True)),
                ('note_body', models.CharField(max_length=2000)),
            ],
        ),
    ]
