# Generated by Django 2.2.3 on 2020-01-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_owner',
            field=models.CharField(choices=[('r', 'Regent'), ('vr', 'Vice Regent'), ('s', 'Scribe'), ('t', 'Treasurer'), ('cs', 'Corresponding Secretary'), ('ig', 'Inner Guard'), ('og', 'Outer Guard'), ('m', 'Marshal'), ('o', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='key',
            name='key_owner',
            field=models.CharField(choices=[('r', 'Regent'), ('vr', 'Vice Regent'), ('s', 'Scribe'), ('t', 'Treasurer'), ('cs', 'Corresponding Secretary'), ('ig', 'Inner Guard'), ('og', 'Outer Guard'), ('m', 'Marshal'), ('o', 'Other')], max_length=2),
        ),
    ]
