# Generated by Django 2.2.3 on 2020-01-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200128_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('bin_name', models.CharField(max_length=20)),
                ('bin_location', models.CharField(max_length=20)),
                ('bin_contents', models.CharField(max_length=200)),
                ('bin_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
