# Generated by Django 2.2.9 on 2020-02-07 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_item_item_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_edited_by',
        ),
        migrations.AddField(
            model_name='item',
            name='item_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='item_last_edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
