# Generated by Django 2.2.3 on 2020-01-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_name', models.CharField(max_length=20)),
                ('note_stamp', models.DateTimeField(auto_now_add=True)),
                ('note_body', models.CharField(max_length=2000)),
            ],
        ),
    ]
