# Generated by Django 2.2.9 on 2020-02-07 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200207_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
