# Generated by Django 2.2.3 on 2020-01-30 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_releasenotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReleaseNotes',
            new_name='ReleaseNote',
        ),
    ]
