# Generated by Django 2.2.3 on 2020-02-05 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200131_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='bin_last_edited_by',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_last_edited_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_last_edited_by',
        ),
        migrations.RemoveField(
            model_name='key',
            name='key_last_edited_by',
        ),
    ]
