# Generated by Django 2.2.3 on 2020-02-05 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_item_item_changed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_changed_by',
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('item_name', models.CharField(max_length=50)),
                ('item_location', models.CharField(max_length=50)),
                ('item_qty', models.IntegerField(default=1)),
                ('item_longdescription', models.CharField(max_length=300)),
                ('item_id', models.IntegerField(blank=True, db_index=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
