# Generated by Django 2.2.3 on 2020-02-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200205_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='item_changed_by',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_changed_by',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
